language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
script:
 - dotnet restore
 - dotnet build 
 - dotnet test ./NeuralNetworks.Tests.UnitTests/NeuralNetworks.Tests.UnitTests.csproj
 - dotnet test ./NeuralNetworks.Tests.IntegrationTests/NeuralNetworks.Tests.IntegrationTests.csproj