language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
 - dotnet build 
 - dotnet test ./NeuralNetworks.Tests.UnitTests/NeuralNetworks.Tests.UnitTests.csproj -c Release
 - dotnet test ./NeuralNetworks.Tests.IntegrationTests/NeuralNetworks.Tests.IntegrationTests.csproj -c Release